### PR TITLE
Bugfix select text on IOS safari

### PR DESCRIPTION
**Pull request by ggianglv**
Hi. I can't find the job post on Upwork. So I created PR here.

- The problem is this layer `<div class="fixed z-10 inset-0" aria-labelledby="modal-title" role="dialog" aria-modal="true">`
- I removed it and change some code.
- If It not working try clear the cache first

### CODE REVIEW

**Comment by jeffreybiles** [comment]
Fantastic work!

Job post is here: https://www.upwork.com/ab/applicants/1441919756573503488/job-details

Go ahead and "apply" there and I'll accept as soon as I see it, "complete" the job, and get you the $500

**Comment by jeffreybiles** [comment]
Ah, I see that I had it on invite-only.  Apologies on that, it should be open now.

**Comment by ggianglv** [comment]
@jeffreybiles I can't access this link https://www.upwork.com/ab/applicants/1441919756573503488/job-details. Or I think you can invite me https://www.upwork.com/freelancers/~01e3607a933293d314. Thanks
image

**Comment by jeffreybiles** [comment]
Ah that must've been the admin link.  Thanks for the patience on that front, this is my first time running a bounty like this.

For anyone else keeping track, we got everything resolved over on Upwork:

Screen Shot 2021-09-26 at 8 21 22 AM

**Pull request merged**
